### PR TITLE
Update .gitignore

### LINKED ISSUE #1: Add new header
asdlfkj asdf
asdf
asdf
dsfds
f
dsf
dsf
dsfds
fdsf
dfs

### PR DESCRIPTION
**Pull request by nenadbugaric**
closes #1

### CODE REVIEW

**Comment by nenadbugaric** [comment]
asdfksadf ]
asdfadsfadsfdsf

**Comment by goran-zobenica** [comment]
All is good

**Comment by nenadbugaric** [comment]
🚀

**Comment by nenadbugaric** [comment]
🚢

**Pull request merged**
